/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spk_pemilihan_siswa_berprestasi;

import javax.swing.JOptionPane;

/**
 *
 * @author Evander Filipi
 */
public class Form_Login extends javax.swing.JFrame {
    private Tampilan_Utama tampilanutama;
    private EnkripsiMD5 enkripsiMD5 = new EnkripsiMD5();

    /**
     * Creates new form Form_Login
     */
    public Form_Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        batalBtn = new javax.swing.JButton();
        passTxt = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Login");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png")).getImage());
        setMinimumSize(new java.awt.Dimension(445, 299));
        setPreferredSize(new java.awt.Dimension(445, 299));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User2.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 90, 20, 30);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 90, 34, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Key.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 150, 20, 30);

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 150, 34, 30);

        jLabel1.setFont(new java.awt.Font("STLiti", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Silahkan Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 230, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 78, 22);

        userTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(userTxt);
        userTxt.setBounds(170, 90, 230, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 150, 74, 22);

        loginBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn);
        loginBtn.setBounds(80, 210, 110, 33);

        batalBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        batalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancel2.png"))); // NOI18N
        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });
        getContentPane().add(batalBtn);
        batalBtn.setBounds(254, 210, 107, 33);

        passTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(passTxt);
        passTxt.setBounds(170, 150, 230, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smp_buglos.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 440, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String usernya = userTxt.getText();
        String passnya = new String (passTxt.getPassword());
        String hashPass = "";
        String pass = "";
        String namaadmin = "";
        int kd_admin = 0;
        String status = "";
        if(usernya.equals("") && passnya.equals("")){
            JOptionPane.showMessageDialog(null, "Input username dan password terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(usernya.equals("")){
                JOptionPane.showMessageDialog(null, "Input username terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            } else {
                if(passnya.equals("")){
                    JOptionPane.showMessageDialog(null, "Input password terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                } else {
                    try{
                        hashPass = enkripsiMD5.hashMD5(new String(passTxt.getPassword()));
                        java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                        java.sql.Statement stm = conn.createStatement();
                        java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_admin where username='"+usernya+"'");
                        if(sql.next()){
                            kd_admin = sql.getInt("kd_admin");
                            pass = sql.getString("password");
                            namaadmin = sql.getString("nama");
                            status = sql.getString("status");
                            if(hashPass.equals(pass)){
                                tampilanutama = new Tampilan_Utama();
                                JOptionPane.showMessageDialog(null, "Login Berhasil!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                                tampilanutama.kd_admin = kd_admin;
                                tampilanutama.jMenu5.setEnabled(true);
                                tampilanutama.jMenuItem1.setEnabled(false);
                                tampilanutama.jMenuItem5.setEnabled(true);
                                tampilanutama.jMenuItem6.setEnabled(true);
                                tampilanutama.jMenuItem7.setEnabled(true);
                                tampilanutama.jMenuItem10.setEnabled(true);
                                tampilanutama.adLbl.setVisible(true);
                                tampilanutama.adminLbl.setVisible(true);
                                tampilanutama.adminLbl.setText(namaadmin);
                                tampilanutama.logoutBtn.setVisible(true);
                                tampilanutama.setVisible(true);
                                this.dispose();
                            } else {
                                JOptionPane.showMessageDialog(null, "Username atau Password salah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                            userTxt.setText("");
                            passTxt.setText("");
                            userTxt.requestFocus();
                            }
                        }
                        else {
                            JOptionPane.showMessageDialog(null, "Username atau password salah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                            userTxt.setText("");
                            passTxt.setText("");
                        }
                    } catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        tampilanutama = new Tampilan_Utama();
        tampilanutama.setVisible(true);
    }//GEN-LAST:event_batalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
