/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spk_pemilihan_siswa_berprestasi;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Evander Filipi
 */
public class Form_Nilai_Siswa extends javax.swing.JFrame {
    int kd_nilai = 0;
    double n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12;
    double ratarata = 0.0;
    String kelas = "";
    String semester = "";
    String tahunajaran="";
    String kategori = "";
    
    private void getDataSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT NIS, Nama, Tgl_Lahir, Jenis_Kelamin  FROM tb_datasiswa");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    private void getNilaiSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaiakademik");
            datanilaiTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    private void getCariNilaiSiswa() {
        if (kategori.equals("") || cari2Txt.equals("")){
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaiakademik");
            datanilaiTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        } else {
            try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaiakademik WHERE "+kategori+" like '%"+cari2Txt.getText()+"%'");
            datanilaiTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
    }
        }
    }

    /**
     * Creates new form Form_Nilai_Siswa
     */
    public Form_Nilai_Siswa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        getDataSiswa();
        getNilaiSiswa();
        nisTxt.setEditable(false);
        namaTxt.setEditable(false);
        ratarataTxt.setEditable(false);
        tahunajaranTxt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        n1Txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        n2Txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        n3Txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        n4Txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        n5Txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        n6Txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        n7Txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        n8Txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        n9Txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nisTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        n10Txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        n11Txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        n12Txt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ratarataTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        semesterCmb = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        tahunajaranCmb = new javax.swing.JComboBox<>();
        tahunajaranTxt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        kelasCmb = new javax.swing.JComboBox<>();
        simpanBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        bersihkanBtn = new javax.swing.JButton();
        prosesBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        refresh1Btn = new javax.swing.JButton();
        cari1Btn = new javax.swing.JButton();
        cari1Txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        datasiswaTbl = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        kategoriCmb = new javax.swing.JComboBox<>();
        cari2Txt = new javax.swing.JTextField();
        cari2Btn = new javax.swing.JButton();
        refresh2Btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        datanilaiTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Nilai Akademik Siswa");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png")).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nilai Akademik Siswa"));

        jLabel4.setText("Pend. Agama");

        jLabel5.setText("PKN");

        jLabel6.setText("B. Indonesia");

        jLabel7.setText("B. Inggris");

        jLabel8.setText("Matematika");

        jLabel9.setText("IPA");

        jLabel10.setText("IPS");

        jLabel11.setText("Seni Budaya");

        jLabel12.setText("Penjaskes");

        jLabel13.setText("NIS");

        jLabel14.setText("Nama Siswa");

        jLabel3.setText("TIK");

        jLabel15.setText("B. Sunda");

        jLabel16.setText("PLH");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Nilai Rata-Rata");

        ratarataTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratarataTxtActionPerformed(evt);
            }
        });

        jLabel31.setText("Semester");

        semesterCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Ganjil", "Genap" }));

        jLabel32.setText("Tahun Ajaran");

        tahunajaranCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "2016/2017", "2017/2018", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "2024/2025", "2025/2026", "2026/2027", "2027/2028", "2028/2029", "2029/2030", "Input Manual" }));
        tahunajaranCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunajaranCmbActionPerformed(evt);
            }
        });

        jLabel30.setText("Kelas");

        kelasCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "VII-A", "VII-B", "VII-C", "VII-D", "VIII-A", "VIII-B", "VIII-C", "VIII-D", "IX-A", "IX-B", "IX-C", "IX-D" }));
        kelasCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasCmbActionPerformed(evt);
            }
        });

        simpanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Upload.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        hapusBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hapusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        bersihkanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bersihkanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clear.png"))); // NOI18N
        bersihkanBtn.setText("Clear");
        bersihkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanBtnActionPerformed(evt);
            }
        });

        prosesBtn.setText("Proses");
        prosesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesBtnActionPerformed(evt);
            }
        });

        infoBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Help.png"))); // NOI18N
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(namaTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(n5Txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(n4Txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n3Txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n2Txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n1Txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n6Txt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(n7Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(n8Txt)
                            .addComponent(n9Txt)
                            .addComponent(n10Txt)
                            .addComponent(n11Txt)
                            .addComponent(n12Txt))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prosesBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ratarataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(semesterCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kelasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(simpanBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bersihkanBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(n1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(n2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(n3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(n4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(n5Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(n6Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(n7Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(n8Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(n9Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(n10Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(n11Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(n12Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ratarataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prosesBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(kelasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(semesterCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanBtn)
                    .addComponent(updateBtn)
                    .addComponent(hapusBtn)
                    .addComponent(bersihkanBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cari NIS atau Nama Siswa");

        refresh1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh1Btn.setText("Refresh");
        refresh1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1BtnActionPerformed(evt);
            }
        });

        cari1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cari1Btn.setText("Cari");
        cari1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1BtnActionPerformed(evt);
            }
        });

        cari1Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        datasiswaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Tanggal Lahir", "Jenis Kelamin"
            }
        ));
        datasiswaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datasiswaTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(datasiswaTbl);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari1Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(refresh1Btn)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refresh1Btn)
                    .addComponent(cari1Btn)
                    .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Siswa", jPanel3);

        kategoriCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kategoriCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Kategori Pencarian-", "NIS", "Nama Siswa", "Kelas", "Semester", "Tahun Ajaran" }));
        kategoriCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriCmbActionPerformed(evt);
            }
        });

        cari2Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cari2Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cari2Btn.setText("Cari");
        cari2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2BtnActionPerformed(evt);
            }
        });

        refresh2Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh2Btn.setText("Refresh");
        refresh2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh2BtnActionPerformed(evt);
            }
        });

        datanilaiTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd_Nilai", "NIS", "Nama", "Agama", "PKN", "B. Indonesia", "B. Inggris", "Matematika", "IPA", "IPS", "Seni Budaya", "Penjaskes", "TIK", "B. Sunda", "PLH", "Nilai Rata-Rata", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        datanilaiTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datanilaiTblMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(datanilaiTbl);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1700, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kategoriCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari2Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refresh2Btn)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoriCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2Btn)
                    .addComponent(refresh2Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3))
        );

        jTabbedPane1.addTab("Data Nilai Akademik Siswa", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here: 
        String nisnya = null;
        String namanya = null;
        String kelasnya = null;
        String semesternya = null;
        
        if (kelasCmb.getSelectedIndex()==0){ 
        kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
        kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
        kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
        kelas="VII-C";}
        else if(kelasCmb.getSelectedIndex()==4){
        kelas="VII-D";}
        else if(kelasCmb.getSelectedIndex()==5){
        kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==6){
        kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==7){
        kelas="VIII-C";}
        else if(kelasCmb.getSelectedIndex()==8){
        kelas="VIII-D";}
        else if(kelasCmb.getSelectedIndex()==9){
        kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==10){
        kelas="IX-B";}
        else if(kelasCmb.getSelectedIndex()==11){
        kelas="IX-C";}
        else if(kelasCmb.getSelectedIndex()==12){
        kelas="IX-D";}
        
        if (semesterCmb.getSelectedIndex()==0){ 
        semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
        semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
        semester="Genap";}
        
        if (tahunajaranCmb.getSelectedIndex()==0){ 
        tahunajaran="";}
        else if(tahunajaranCmb.getSelectedIndex()==1){
        tahunajaran="2016/2017";}
        else if(tahunajaranCmb.getSelectedIndex()==2){
        tahunajaran="2017/2018";}
        else if(tahunajaranCmb.getSelectedIndex()==3){
        tahunajaran="2018/2019";}
        else if(tahunajaranCmb.getSelectedIndex()==4){
        tahunajaran="2019/2020";}
        else if(tahunajaranCmb.getSelectedIndex()==5){
        tahunajaran="2020/2021";}
        else if(tahunajaranCmb.getSelectedIndex()==6){
        tahunajaran="2021/2022";}
        else if(tahunajaranCmb.getSelectedIndex()==7){
        tahunajaran="2022/2023";}
        else if(tahunajaranCmb.getSelectedIndex()==8){
        tahunajaran="2023/2024";}
        else if(tahunajaranCmb.getSelectedIndex()==9){
        tahunajaran="2024/2025";}
        else if(tahunajaranCmb.getSelectedIndex()==10){
        tahunajaran="2025/2026";}
        else if(tahunajaranCmb.getSelectedIndex()==11){
        tahunajaran="2026/2027";}
        else if(tahunajaranCmb.getSelectedIndex()==12){
        tahunajaran="2027/2028";}
        else if(tahunajaranCmb.getSelectedIndex()==13){
        tahunajaran="2028/2029";}
        else if(tahunajaranCmb.getSelectedIndex()==14){
        tahunajaran="2029/2030";}
        else if(tahunajaranCmb.getSelectedIndex()==15){
        tahunajaran=tahunajaranTxt.getText();}
        
        if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || n1Txt.getText().equals("") || n2Txt.getText().equals("") || n3Txt.getText().equals("") || n4Txt.getText().equals("") || n5Txt.getText().equals("") || n6Txt.getText().equals("") ||
                n7Txt.getText().equals("") || n8Txt.getText().equals("") || n9Txt.getText().equals("") || n10Txt.getText().equals("") || n11Txt.getText().equals("") || n12Txt.getText().equals("") || ratarataTxt.getText().equals("") || kelas.equals("") || semester.equals("") || tahunajaran.equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
        n1 = Double.parseDouble(n1Txt.getText());
        n2 = Double.parseDouble(n2Txt.getText());
        n3 = Double.parseDouble(n3Txt.getText());
        n4 = Double.parseDouble(n4Txt.getText());
        n5 = Double.parseDouble(n5Txt.getText());
        n6 = Double.parseDouble(n6Txt.getText());
        n7 = Double.parseDouble(n7Txt.getText());
        n8 = Double.parseDouble(n8Txt.getText());
        n9 = Double.parseDouble(n9Txt.getText());
        n10 = Double.parseDouble(n10Txt.getText());
        n11 = Double.parseDouble(n11Txt.getText());
        n12 = Double.parseDouble(n12Txt.getText());
        ratarata = Double.parseDouble(ratarataTxt.getText());
        try {
           java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
           java.sql.Statement stm = conn.createStatement();
           java.sql.ResultSet sqll = stm.executeQuery("SELECT NIS, Nama, Kelas, Semester FROM tb_nilaiakademik WHERE NIS='"+nisTxt.getText()+"' AND Kelas='"+kelas+"' AND Semester='"+semester+"'");        
           if (sqll.next()) {
               int niss = sqll.getInt("NIS");
               nisnya = Integer.toString(niss);
               namanya = sqll.getString("Nama");
               kelasnya = sqll.getString("Kelas");
               semesternya = sqll.getString("Semester");
           } else {}
           if (nisTxt.getText().equals(nisnya) && kelas.equals(kelasnya) && semester.equals(semesternya)){
           JOptionPane.showMessageDialog(null, "Nilai akademik "+namaTxt.getText()+" kelas "+kelas+" pada semester "+semester+" sudah ada!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);    
           } else {
                String sql = "INSERT INTO tb_nilaiakademik VALUES('"+kd_nilai+"','"+nisTxt.getText()+"','"+namaTxt.getText()+"','"+n1+"','"+n2+"','"+n3+"','"+n4+"','"+n5+"','"+n6+"','"+n7+"','"+n8+"','"+n9+"','"+n10+"',"
                        + "'"+n11+"','"+n12+"','"+ratarata+"','"+kelas+"','"+semester+"','"+tahunajaran+"')";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Nilai akademik siswa berhasil disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
           }
        } catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Nilai akademik siswa gagal disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        }
        getNilaiSiswa();
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void prosesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesBtnActionPerformed
        // TODO add your handling code here:
        n1 = Double.parseDouble(n1Txt.getText());
        n2 = Double.parseDouble(n2Txt.getText());
        n3 = Double.parseDouble(n3Txt.getText());
        n4 = Double.parseDouble(n4Txt.getText());
        n5 = Double.parseDouble(n5Txt.getText());
        n6 = Double.parseDouble(n6Txt.getText());
        n7 = Double.parseDouble(n7Txt.getText());
        n8 = Double.parseDouble(n8Txt.getText());
        n9 = Double.parseDouble(n9Txt.getText());
        n10 = Double.parseDouble(n10Txt.getText());
        n11 = Double.parseDouble(n11Txt.getText());
        n12 = Double.parseDouble(n12Txt.getText());
        double jumlah = n1+n2+n3+n4+n5+n6+n7+n8+n9+n10+n11+n12;
        ratarata = jumlah/12;
        ratarata = Math.round(ratarata * 100);
        ratarata = ratarata/100;
        ratarataTxt.setText(Double.toString(ratarata));
    }//GEN-LAST:event_prosesBtnActionPerformed

    private void ratarataTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratarataTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratarataTxtActionPerformed

    private void tahunajaranCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunajaranCmbActionPerformed
        // TODO add your handling code here:\
        if (tahunajaranCmb.getSelectedIndex()==0){ 
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==1){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==2){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==3){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==4){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==5){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==6){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==7){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==8){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==9){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==10){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==11){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==12){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==13){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==14){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==15){
        tahunajaranTxt.setEnabled(true);}
    }//GEN-LAST:event_tahunajaranCmbActionPerformed

    private void datasiswaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datasiswaTblMouseClicked
        // TODO add your handling code here:
        try {
           int row = datasiswaTbl.getSelectedRow();
           String kliktabel=(datasiswaTbl.getModel().getValueAt(row,0).toString());
           java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
           java.sql.Statement stm = conn.createStatement();
           java.sql.ResultSet sql = stm.executeQuery("SELECT NIS, Nama FROM tb_datasiswa WHERE NIS='"+kliktabel+"'");
           
           if (sql.next()) {
               int nis = sql.getInt("NIS");
               String nisString = Integer.toString(nis);
               nisTxt.setText(nisString);
               String nama = sql.getString("Nama");
               namaTxt.setText(nama);
           }           
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_datasiswaTblMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String kelas = null;
        if (kelasCmb.getSelectedIndex()==0){ 
        kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
        kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
        kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
        kelas="VII-C";}
        else if(kelasCmb.getSelectedIndex()==4){
        kelas="VII-D";}
        else if(kelasCmb.getSelectedIndex()==5){
        kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==6){
        kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==7){
        kelas="VIII-C";}
        else if(kelasCmb.getSelectedIndex()==8){
        kelas="VIII-D";}
        else if(kelasCmb.getSelectedIndex()==9){
        kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==10){
        kelas="IX-B";}
        else if(kelasCmb.getSelectedIndex()==11){
        kelas="IX-C";}
        else if(kelasCmb.getSelectedIndex()==12){
        kelas="IX-D";}
        
        String semester = null;
        if (semesterCmb.getSelectedIndex()==0){ 
        semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
        semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
        semester="Genap";}
        
        String tahunajaran = null;
        if (tahunajaranCmb.getSelectedIndex()==0){ 
        tahunajaran="";}
        else if(tahunajaranCmb.getSelectedIndex()==1){
        tahunajaran="2016/2017";}
        else if(tahunajaranCmb.getSelectedIndex()==2){
        tahunajaran="2017/2018";}
        else if(tahunajaranCmb.getSelectedIndex()==3){
        tahunajaran="2018/2019";}
        else if(tahunajaranCmb.getSelectedIndex()==4){
        tahunajaran="2019/2020";}
        else if(tahunajaranCmb.getSelectedIndex()==5){
        tahunajaran="2020/2021";}
        else if(tahunajaranCmb.getSelectedIndex()==6){
        tahunajaran="2021/2022";}
        else if(tahunajaranCmb.getSelectedIndex()==7){
        tahunajaran="2022/2023";}
        else if(tahunajaranCmb.getSelectedIndex()==8){
        tahunajaran="2023/2024";}
        else if(tahunajaranCmb.getSelectedIndex()==9){
        tahunajaran="2024/2025";}
        else if(tahunajaranCmb.getSelectedIndex()==10){
        tahunajaran="2025/2026";}
        else if(tahunajaranCmb.getSelectedIndex()==11){
        tahunajaran="2026/2027";}
        else if(tahunajaranCmb.getSelectedIndex()==12){
        tahunajaran="2027/2028";}
        else if(tahunajaranCmb.getSelectedIndex()==13){
        tahunajaran="2028/2029";}
        else if(tahunajaranCmb.getSelectedIndex()==14){
        tahunajaran="2029/2030";}
        else if(tahunajaranCmb.getSelectedIndex()==15){
        tahunajaran=tahunajaranTxt.getText();}
        
        if (kd_nilai == 0){
            JOptionPane.showMessageDialog(null, "Pilih nilai akademik siswa yang ingin diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
        if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || n1Txt.getText().equals("") || n2Txt.getText().equals("") || n3Txt.getText().equals("") || n4Txt.getText().equals("") || n5Txt.getText().equals("") || n6Txt.getText().equals("") ||
                n7Txt.getText().equals("") || n8Txt.getText().equals("") || n9Txt.getText().equals("") || n10Txt.getText().equals("") || n11Txt.getText().equals("") || n12Txt.getText().equals("") || ratarataTxt.getText().equals("") || kelas.equals("") || semester.equals("") || tahunajaran.equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
        n1 = Double.parseDouble(n1Txt.getText());
        n2 = Double.parseDouble(n2Txt.getText());
        n3 = Double.parseDouble(n3Txt.getText());
        n4 = Double.parseDouble(n4Txt.getText());
        n5 = Double.parseDouble(n5Txt.getText());
        n6 = Double.parseDouble(n6Txt.getText());
        n7 = Double.parseDouble(n7Txt.getText());
        n8 = Double.parseDouble(n8Txt.getText());
        n9 = Double.parseDouble(n9Txt.getText());
        n10 = Double.parseDouble(n10Txt.getText());
        n11 = Double.parseDouble(n11Txt.getText());
        n12 = Double.parseDouble(n12Txt.getText());
        ratarata = Double.parseDouble(ratarataTxt.getText());
        try {
           java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
           String sql = "UPDATE tb_nilaiakademik SET NIS='"+nisTxt.getText()+"', Nama='"+namaTxt.getText()+"', Agama='"+n1+"', PKN='"+n2+"', B_Indonesia='"+n3+"', B_Inggris='"+n4+"', Matematika='"+n5+"', IPA='"+n6+"', IPS='"+n7+"', Seni_Budaya='"+n8+"', Penjaskes='"+n9+"', TIK='"+n10+"',"
                        + " B_Sunda='"+n11+"', PLH='"+n12+"', Nilai_Ratarata='"+ratarata+"', Kelas='"+kelas+"', Semester='"+semester+"', Tahun_Ajaran='"+tahunajaran+"' WHERE kd_nilai ='"+kd_nilai+"'";
           java.sql.PreparedStatement pst = conn.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(null, "Nilai akademik siswa berhasil diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Nilai akademik siswa gagal diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        }
        getCariNilaiSiswa();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void datanilaiTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datanilaiTblMouseClicked
        // TODO add your handling code here:
        try {
            int row = datanilaiTbl.getSelectedRow();
            String kliktabel=(datanilaiTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaiakademik WHERE kd_nilai='"+kliktabel+"'");

            if (sql.next()) {
                kd_nilai = sql.getInt("kd_nilai");
                int nis = sql.getInt("NIS");
                String nisString = Integer.toString(nis);
                nisTxt.setText(nisString);
                String nama = sql.getString("Nama");
                namaTxt.setText(nama);
                double nilai1 = sql.getDouble("Agama");
                String agama = Double.toString(nilai1);
                n1Txt.setText(agama);
                double nilai2 = sql.getDouble("PKN");
                String pkn = Double.toString(nilai2);
                n2Txt.setText(pkn);
                double nilai3 = sql.getDouble("B_Indonesia");
                String b_indo = Double.toString(nilai3);
                n3Txt.setText(b_indo);
                double nilai4 = sql.getDouble("B_Inggris");
                String b_ing = Double.toString(nilai4);
                n4Txt.setText(b_ing);
                double nilai5 = sql.getDouble("Matematika");
                String mtk = Double.toString(nilai5);
                n5Txt.setText(mtk);
                double nilai6 = sql.getDouble("IPA");
                String ipa = Double.toString(nilai6);
                n6Txt.setText(ipa);
                double nilai7 = sql.getDouble("IPS");
                String ips = Double.toString(nilai7);
                n7Txt.setText(ips);
                double nilai8 = sql.getDouble("Seni_Budaya");
                String senbud = Double.toString(nilai8);
                n8Txt.setText(senbud);
                double nilai9 = sql.getDouble("Penjaskes");
                String penjas = Double.toString(nilai9);
                n9Txt.setText(penjas);
                double nilai10 = sql.getDouble("TIK");
                String tik = Double.toString(nilai10);
                n10Txt.setText(tik);
                double nilai11 = sql.getDouble("B_Sunda");
                String b_sunda = Double.toString(nilai11);
                n11Txt.setText(b_sunda);
                double nilai12 = sql.getDouble("PLH");
                String plh = Double.toString(nilai12);
                n12Txt.setText(plh);
                double nilairata = sql.getDouble("Nilai_Ratarata");
                String n_rata2 = Double.toString(nilairata);
                ratarataTxt.setText(n_rata2);
                
                String kls = sql.getString("Kelas");
                if(kls.equals("")){
                    kelasCmb.setSelectedIndex(0);}
                else if(kls.equals("VII-A")){
                    kelasCmb.setSelectedIndex(1);}
                else if(kls.equals("VII-B")){
                    kelasCmb.setSelectedIndex(2);}
                else if(kls.equals("VII-C")){
                    kelasCmb.setSelectedIndex(3);}
                else if(kls.equals("VII-D")){
                    kelasCmb.setSelectedIndex(4);}
                else if(kls.equals("VIII-A")){
                    kelasCmb.setSelectedIndex(5);}
                else if(kls.equals("VIII-B")){
                    kelasCmb.setSelectedIndex(6);}
                else if(kls.equals("VIII-C")){
                    kelasCmb.setSelectedIndex(7);}
                else if(kls.equals("VIII-D")){
                    kelasCmb.setSelectedIndex(8);}
                else if(kls.equals("IX-A")){
                    kelasCmb.setSelectedIndex(9);}
                else if(kls.equals("IX-B")){
                    kelasCmb.setSelectedIndex(10);}
                else if(kls.equals("IX-C")){
                    kelasCmb.setSelectedIndex(11);}
                else if(kls.equals("IX-D")){
                    kelasCmb.setSelectedIndex(12);}
                
                String smstr = sql.getString("Semester");
                if(smstr.equals("")){
                    semesterCmb.setSelectedIndex(0);}
                else if(smstr.equals("Ganjil")){
                    semesterCmb.setSelectedIndex(1);}
                else if(smstr.equals("Genap")){
                    semesterCmb.setSelectedIndex(2);}
                
                String thnajaran = sql.getString("Tahun_Ajaran");
                if(thnajaran.equals("")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(0);}
                else if(thnajaran.equals("2016/2017")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(1);}
                else if(thnajaran.equals("2017/2018")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(2);}
                else if(thnajaran.equals("2018/2019")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(3);}
                else if(thnajaran.equals("2019/2020")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(4);}
                else if(thnajaran.equals("2020/2021")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(5);}
                else if(thnajaran.equals("2021/2022")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(6);}
                else if(thnajaran.equals("2022/2023")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(7);}
                else if(thnajaran.equals("2023/2024")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(8);}
                else if(thnajaran.equals("2024/2025")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(9);}
                else if(thnajaran.equals("2025/2026")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(10);}
                else if(thnajaran.equals("2026/2027")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(11);}
                else if(thnajaran.equals("2027/2028")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(12);}
                else if(thnajaran.equals("2028/2029")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(13);}
                else if(thnajaran.equals("2029/2030")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(14);}
                else{
                    tahunajaranTxt.setEnabled(true);
                    tahunajaranTxt.setText(thnajaran);
                    tahunajaranCmb.setSelectedIndex(15);
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_datanilaiTblMouseClicked

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        if (kd_nilai == 0){
            JOptionPane.showMessageDialog(null, "Pilih nilai akademik siswa yang ingin dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
        Object[] options = {"Iya", "Tidak"};
            int van = JOptionPane.showOptionDialog(this, "Anda yakin ingin menghapus data nilai akademik "+namaTxt.getText()+"?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if(van== 0){
        try {
            String sql = "DELETE FROM tb_nilaiakademik WHERE kd_nilai='"+kd_nilai+"'";
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Nilai akademik siswa berhasil dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(null, "Nilai akademik siswa gagal dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        getCariNilaiSiswa();}
            else if(van== 1){
        }
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void bersihkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanBtnActionPerformed
        // TODO add your handling code here:
        kd_nilai = 0;
        nisTxt.setText("");
        namaTxt.setText("");
        n1Txt.setText("");
        n2Txt.setText("");
        n3Txt.setText("");
        n4Txt.setText("");
        n5Txt.setText("");
        n6Txt.setText("");
        n7Txt.setText("");
        n8Txt.setText("");
        n9Txt.setText("");
        n10Txt.setText("");
        n11Txt.setText("");
        n12Txt.setText("");
        ratarataTxt.setText("");
        kelasCmb.setSelectedIndex(0);
        semesterCmb.setSelectedIndex(0);
        tahunajaranCmb.setSelectedIndex(0);
    }//GEN-LAST:event_bersihkanBtnActionPerformed

    private void cari1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1BtnActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT NIS, Nama, Tgl_Lahir, Jenis_Kelamin FROM tb_datasiswa WHERE NIS like '%"+cari1Txt.getText()+"%' or Nama like '%"+cari1Txt.getText()+"%'");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cari1BtnActionPerformed

    private void refresh1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1BtnActionPerformed
        // TODO add your handling code here:
        getDataSiswa();
        cari1Txt.setText("");
    }//GEN-LAST:event_refresh1BtnActionPerformed

    private void kategoriCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriCmbActionPerformed
        // TODO add your handling code here:
        if (kategoriCmb.getSelectedIndex()==0){ 
        kategori="";}
        else if(kategoriCmb.getSelectedIndex()==1){
        kategori="NIS";}
        else if(kategoriCmb.getSelectedIndex()==2){
        kategori="Nama";}
        else if(kategoriCmb.getSelectedIndex()==3){
        kategori="Kelas";}
        else if(kategoriCmb.getSelectedIndex()==4){
        kategori="Semester";}
        else if(kategoriCmb.getSelectedIndex()==5){
        kategori="Tahun_Ajaran";}
    }//GEN-LAST:event_kategoriCmbActionPerformed

    private void cari2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2BtnActionPerformed
        // TODO add your handling code here:
        if (kategori.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih kategori pencarian terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaiakademik WHERE "+kategori+" like '%"+cari2Txt.getText()+"%'");
            datanilaiTbl.setModel(DbUtils.resultSetToTableModel(sql));   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_cari2BtnActionPerformed

    private void refresh2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh2BtnActionPerformed
        // TODO add your handling code here:
        cari2Txt.setText("");
        kategoriCmb.setSelectedIndex(0);
        getNilaiSiswa();
    }//GEN-LAST:event_refresh2BtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Lihat petunjuk pada tampilan utama aplikasi ini.","Petunjuk",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_infoBtnActionPerformed

    private void kelasCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Nilai_Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkanBtn;
    private javax.swing.JButton cari1Btn;
    private javax.swing.JTextField cari1Txt;
    private javax.swing.JButton cari2Btn;
    private javax.swing.JTextField cari2Txt;
    private javax.swing.JTable datanilaiTbl;
    private javax.swing.JTable datasiswaTbl;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JButton infoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> kategoriCmb;
    private javax.swing.JComboBox<String> kelasCmb;
    private javax.swing.JTextField n10Txt;
    private javax.swing.JTextField n11Txt;
    private javax.swing.JTextField n12Txt;
    private javax.swing.JTextField n1Txt;
    private javax.swing.JTextField n2Txt;
    private javax.swing.JTextField n3Txt;
    private javax.swing.JTextField n4Txt;
    private javax.swing.JTextField n5Txt;
    private javax.swing.JTextField n6Txt;
    private javax.swing.JTextField n7Txt;
    private javax.swing.JTextField n8Txt;
    private javax.swing.JTextField n9Txt;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField nisTxt;
    private javax.swing.JButton prosesBtn;
    private javax.swing.JTextField ratarataTxt;
    private javax.swing.JButton refresh1Btn;
    private javax.swing.JButton refresh2Btn;
    private javax.swing.JComboBox<String> semesterCmb;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JComboBox<String> tahunajaranCmb;
    private javax.swing.JTextField tahunajaranTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
