/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spk_pemilihan_siswa_berprestasi;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Evander Filipi
 */
public class Form_Kriteria extends javax.swing.JFrame {
    int kd_nilai = 0;
    int kd_alternatif = 0;
    double k1d, k2d, k3d, k4d, k5d, k6d;
    String kategori1 = "";
    String kategori2 = "";
    
    private void getNilaiSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT Kd_Nilai, NIS, Nama, Nilai_Ratarata, Kelas, Semester, Tahun_Ajaran FROM tb_nilaiakademik");
            nilaiakademikTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    private void getKriteriaSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT kd_alternatif, NIS, Nama, Kedisiplinan, Kepribadian, Kerapihan, Ekstrakulikuler, Absensi, Akademik, Kelas, Semester, Tahun_Ajaran FROM tb_nilaikriteria");
            nilaikriteriaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    private void getCariKriteriaSiswa() {
        if (kategori2.equals("") || cari2Txt.getText().equals("")){
            try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT kd_alternatif, NIS, Nama, Kedisiplinan, Kepribadian, Kerapihan, Ekstrakulikuler, Absensi, Akademik, Kelas, Semester, Tahun_Ajaran FROM tb_nilaikriteria");
            nilaikriteriaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
        } else {
            try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT kd_alternatif, NIS, Nama, Kedisiplinan, Kepribadian, Kerapihan, Ekstrakulikuler, Absensi, Akademik, Kelas, Semester, Tahun_Ajaran FROM tb_nilaikriteria WHERE "+kategori2+" like '%"+cari2Txt.getText()+"%'");
            nilaikriteriaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
    }
        }
    }
    
    private void absensi(){
        if(!nk5Txt.getText().equals("")){
            if(nk5Txt.getText().equals("4.0")){
                kriteria5Txt.setText("Sangat Baik");
            } else if(nk5Txt.getText().equals("3.0")){
                kriteria5Txt.setText("Baik");
            } else if(nk5Txt.getText().equals("2.0")){
                kriteria5Txt.setText("Cukup Baik");
            } else if(nk5Txt.getText().equals("1.0")){
                kriteria5Txt.setText("Buruk");
            } else if(nk5Txt.getText().equals("0.0")){
                kriteria5Txt.setText("Sangat Buruk");
            }
        }
    }

    /**
     * Creates new form Form_Kriteria
     */
    public Form_Kriteria() {
        initComponents();
        getNilaiSiswa();
        getKriteriaSiswa();
        nisTxt.setEditable(false);
        namaTxt.setEditable(false);
        kelasTxt.setEditable(false);
        semesterTxt.setEditable(false);
        tahunajaranTxt.setEditable(false);
        kriteria5Txt.setEditable(false);
        kriteria6Txt.setEditable(false);
        nk1Txt.setEditable(false);
        nk2Txt.setEditable(false);
        nk3Txt.setEditable(false);
        nk4Txt.setEditable(false);
        nk5Txt.setEditable(false);
        nk6Txt.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nisTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kelasTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        semesterTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tahunajaranTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kriteria1Cmb = new javax.swing.JComboBox<>();
        kriteria2Cmb = new javax.swing.JComboBox<>();
        kriteria3Cmb = new javax.swing.JComboBox<>();
        kriteria4Cmb = new javax.swing.JComboBox<>();
        kriteria5Cmb = new javax.swing.JComboBox<>();
        kriteria6Txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nk1Txt = new javax.swing.JTextField();
        nk2Txt = new javax.swing.JTextField();
        nk3Txt = new javax.swing.JTextField();
        nk4Txt = new javax.swing.JTextField();
        nk5Txt = new javax.swing.JTextField();
        nk6Txt = new javax.swing.JTextField();
        simpanBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        bersihkanBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        kriteria5Txt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        kategoricari1Cmb = new javax.swing.JComboBox<>();
        cari1Txt = new javax.swing.JTextField();
        cari1Btn = new javax.swing.JButton();
        refresh1Btn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        nilaiakademikTbl = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        kategoricari2Cmb = new javax.swing.JComboBox<>();
        cari2Txt = new javax.swing.JTextField();
        cari2Btn = new javax.swing.JButton();
        refresh2Btn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        nilaikriteriaTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Kriteria Siswa");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png")).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nilai Kriteria Siswa"));

        jLabel1.setText("NIS");

        jLabel2.setText("Nama");

        jLabel3.setText("Kelas");

        jLabel4.setText("Semester");

        jLabel5.setText("Tahun Ajaran");

        jLabel6.setText("Kedisiplinan");

        jLabel7.setText("Kepribadian");

        jLabel8.setText("Kerapihan");

        jLabel9.setText("Ekstrakulikuler");

        jLabel10.setText("Absensi");

        jLabel13.setText("Akademik");

        kriteria1Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Sangat Baik (A)", "Baik (B)", "Cukup Baik (C)", "Buruk (D)", "Sangat Buruk (E)" }));
        kriteria1Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kriteria1CmbActionPerformed(evt);
            }
        });

        kriteria2Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Sangat Baik (A)", "Baik (B)", "Cukup Baik (C)", "Buruk (D)", "Sangat Buruk (E)" }));
        kriteria2Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kriteria2CmbActionPerformed(evt);
            }
        });

        kriteria3Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Sangat Baik (A)", "Baik (B)", "Cukup Baik (C)", "Buruk (D)", "Sangat Buruk (E)" }));
        kriteria3Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kriteria3CmbActionPerformed(evt);
            }
        });

        kriteria4Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Sangat Aktif (A)", "Aktif (B)", "Cukup Aktif (C)", "Kurang Aktif (D)", "Tidak Ikut (E)" }));
        kriteria4Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kriteria4CmbActionPerformed(evt);
            }
        });

        kriteria5Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Ketidakhadiran-", "0-2 Kali Tidak Hadir", "3-5 Kali Tidak Hadir", "6-9 Kali Tidak Hadir", "10-13 Kali Tidak Hadir", ">13 Kali Tidak Hadir" }));
        kriteria5Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kriteria5CmbActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText(" - Kriteria -");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("- Nilai -");

        nk1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nk1TxtActionPerformed(evt);
            }
        });

        simpanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Upload.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        hapusBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hapusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        bersihkanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bersihkanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clear.png"))); // NOI18N
        bersihkanBtn.setText("Clear");
        bersihkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Help.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tahunajaranTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(semesterTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kelasTxt, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(simpanBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bersihkanBtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kriteria5Txt)
                                    .addComponent(kriteria6Txt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(kriteria5Cmb, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kriteria4Cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kriteria3Cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kriteria2Cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kriteria1Cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel14)))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nk2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nk1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nk3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nk4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nk6Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(nk5Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kelasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(semesterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nk1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kriteria1Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kriteria2Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(nk2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kriteria3Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(nk3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kriteria4Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(nk4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kriteria5Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kriteria5Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nk5Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kriteria6Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nk6Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanBtn)
                    .addComponent(updateBtn)
                    .addComponent(hapusBtn)
                    .addComponent(bersihkanBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        kategoricari1Cmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kategoricari1Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Kategori Pencarian-", "NIS", "Nama", "Kelas", "Semester", "Tahun Ajaran" }));
        kategoricari1Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoricari1CmbActionPerformed(evt);
            }
        });

        cari1Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cari1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cari1Btn.setText("Cari");
        cari1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1BtnActionPerformed(evt);
            }
        });

        refresh1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh1Btn.setText("Refresh");
        refresh1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1BtnActionPerformed(evt);
            }
        });

        nilaiakademikTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd_Nilai", "NIS", "Nama", "Nilai Rata-rata", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        nilaiakademikTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nilaiakademikTblMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(nilaiakademikTbl);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jScrollPane6.setViewportView(jPanel10);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kategoricari1Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari1Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(refresh1Btn)
                .addContainerGap())
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoricari1Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari1Btn)
                    .addComponent(refresh1Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Data Nilai Akademik Siswa", jPanel7);

        kategoricari2Cmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kategoricari2Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Kategori Pencarian-", "NIS", "Nama", "Kelas", "Semester", "Tahun Ajaran" }));
        kategoricari2Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoricari2CmbActionPerformed(evt);
            }
        });

        cari2Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cari2Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cari2Btn.setText("Cari");
        cari2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2BtnActionPerformed(evt);
            }
        });

        refresh2Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh2Btn.setText("Refresh");
        refresh2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh2BtnActionPerformed(evt);
            }
        });

        nilaikriteriaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd_Alternatif", "NIS", "Nama", "Kedisiplinan", "Kepribadian", "Kerapihan", "Ekstrakulikuler", "Absensi", "Akademik", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        nilaikriteriaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nilaikriteriaTblMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(nilaikriteriaTbl);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(jPanel9);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kategoricari2Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari2Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(refresh2Btn)
                .addContainerGap())
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoricari2Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2Btn)
                    .addComponent(refresh2Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Data Nilai Kriteria Siswa", jPanel8);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nk1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nk1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nk1TxtActionPerformed

    private void nilaiakademikTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nilaiakademikTblMouseClicked
        // TODO add your handling code here:
        try {
           int row = nilaiakademikTbl.getSelectedRow();
           String kliktabel=(nilaiakademikTbl.getModel().getValueAt(row,0).toString());
           java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
           java.sql.Statement stm = conn.createStatement();
           java.sql.ResultSet sql = stm.executeQuery("SELECT Kd_Nilai, NIS, Nama, Nilai_Ratarata, Kelas, Semester, Tahun_Ajaran FROM tb_nilaiakademik WHERE Kd_Nilai='"+kliktabel+"'");
           
           if (sql.next()) {
               kd_nilai = sql.getInt("Kd_Nilai");
               int nis = sql.getInt("NIS");
               String nisString = Integer.toString(nis);
               nisTxt.setText(nisString);
               String nama = sql.getString("Nama");
               namaTxt.setText(nama);
               String kelas = sql.getString("Kelas");
               kelasTxt.setText(kelas);
               String semester = sql.getString("Semester");
               semesterTxt.setText(semester);
               String tahunajaran = sql.getString("Tahun_Ajaran");
               tahunajaranTxt.setText(tahunajaran);
               double n_rata = sql.getDouble("Nilai_Ratarata");
               String k8 = null;
               if (n_rata <= 100 && n_rata >= 90){
                   kriteria6Txt.setText("Sangat Baik");
                   k8="4.0";
               } else if (n_rata < 90 && n_rata >= 80){
                   kriteria6Txt.setText("Baik");
                   k8="3.0";
               } else if (n_rata < 80 && n_rata >= 70){
                   kriteria6Txt.setText("Cukup Baik");
                   k8="2.0";
               } else if (n_rata < 70 && n_rata >= 50){
                   kriteria6Txt.setText("Buruk");
                   k8="1.0";
               } else if (n_rata < 50 && n_rata >= 0){
                   kriteria6Txt.setText("Sangat Buruk");
                   k8="0.0";
               }
               nk6Txt.setText(k8);
           }           
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_nilaiakademikTblMouseClicked

    private void kriteria1CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kriteria1CmbActionPerformed
        // TODO add your handling code here:
        String k1 = "";
        if (kriteria1Cmb.getSelectedIndex()==0){ 
            k1="";}
        else if(kriteria1Cmb.getSelectedIndex()==1){
            k1="4.0";}
        else if(kriteria1Cmb.getSelectedIndex()==2){
            k1="3.0";}
        else if(kriteria1Cmb.getSelectedIndex()==3){
            k1="2.0";}
        else if(kriteria1Cmb.getSelectedIndex()==4){
            k1="1.0";}
        else if(kriteria1Cmb.getSelectedIndex()==5){
            k1="0.0";}
        nk1Txt.setText(k1);
    }//GEN-LAST:event_kriteria1CmbActionPerformed

    private void kriteria2CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kriteria2CmbActionPerformed
        // TODO add your handling code here:
        String k2 = "";
        if (kriteria2Cmb.getSelectedIndex()==0){ 
            k2="";}
        else if(kriteria2Cmb.getSelectedIndex()==1){
            k2="4.0";}
        else if(kriteria2Cmb.getSelectedIndex()==2){
            k2="3.0";}
        else if(kriteria2Cmb.getSelectedIndex()==3){
            k2="2.0";}
        else if(kriteria2Cmb.getSelectedIndex()==4){
            k2="1.0";}
        else if(kriteria2Cmb.getSelectedIndex()==5){
            k2="0.0";}
        nk2Txt.setText(k2);
    }//GEN-LAST:event_kriteria2CmbActionPerformed

    private void kriteria3CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kriteria3CmbActionPerformed
        // TODO add your handling code here:
        String k3 = "";
        if (kriteria3Cmb.getSelectedIndex()==0){ 
            k3="";}
        else if(kriteria3Cmb.getSelectedIndex()==1){
            k3="4.0";}
        else if(kriteria3Cmb.getSelectedIndex()==2){
            k3="3.0";}
        else if(kriteria3Cmb.getSelectedIndex()==3){
            k3="2.0";}
        else if(kriteria3Cmb.getSelectedIndex()==4){
            k3="1.0";}
        else if(kriteria3Cmb.getSelectedIndex()==5){
            k3="0.0";}
        nk3Txt.setText(k3);
    }//GEN-LAST:event_kriteria3CmbActionPerformed

    private void kriteria4CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kriteria4CmbActionPerformed
        // TODO add your handling code here:
        String k4 = "";
        if (kriteria4Cmb.getSelectedIndex()==0){ 
            k4="";}
        else if(kriteria4Cmb.getSelectedIndex()==1){
            k4="4.0";}
        else if(kriteria4Cmb.getSelectedIndex()==2){
            k4="3.0";}
        else if(kriteria4Cmb.getSelectedIndex()==3){
            k4="2.0";}
        else if(kriteria4Cmb.getSelectedIndex()==4){
            k4="1.0";}
        else if(kriteria4Cmb.getSelectedIndex()==5){
            k4="0.0";}
        nk4Txt.setText(k4);
    }//GEN-LAST:event_kriteria4CmbActionPerformed

    private void kriteria5CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kriteria5CmbActionPerformed
        // TODO add your handling code here:
        String k5 = "";
        if (kriteria5Cmb.getSelectedIndex()==0){
            k5="";
            kriteria5Txt.setText("");}
        else if(kriteria5Cmb.getSelectedIndex()==1){
            k5="4.0";}
        else if(kriteria5Cmb.getSelectedIndex()==2){
            k5="3.0";}
        else if(kriteria5Cmb.getSelectedIndex()==3){
            k5="2.0";}
        else if(kriteria5Cmb.getSelectedIndex()==4){
            k5="1.0";}
        else if(kriteria5Cmb.getSelectedIndex()==5){
            k5="0.0";}
        nk5Txt.setText(k5);        
        absensi();
    }//GEN-LAST:event_kriteria5CmbActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        String nisnya = null;
        String namanya = null;
        String kelasnya = null;
        String semesternya = null;
        if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || kelasTxt.getText().equals("") || semesterTxt.getText().equals("") || tahunajaranTxt.getText().equals("")
                || nk1Txt.getText().equals("") || nk2Txt.getText().equals("") || nk3Txt.getText().equals("") || nk4Txt.getText().equals("") || nk5Txt.getText().equals("")
                || nk6Txt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            k1d = Double.parseDouble(nk1Txt.getText());
            k2d = Double.parseDouble(nk2Txt.getText());
            k3d = Double.parseDouble(nk3Txt.getText());
            k4d = Double.parseDouble(nk4Txt.getText());
            k5d = Double.parseDouble(nk5Txt.getText());
            k6d = Double.parseDouble(nk6Txt.getText());
        try {
           java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
           java.sql.Statement stm = conn.createStatement();
           java.sql.ResultSet sqll = stm.executeQuery("SELECT NIS, Nama, Kelas, Semester FROM tb_nilaikriteria WHERE NIS='"+nisTxt.getText()+"' AND Kelas='"+kelasTxt.getText()+"' AND Semester='"+semesterTxt.getText()+"'");        
           if (sqll.next()) {
               int niss = sqll.getInt("NIS");
               nisnya = Integer.toString(niss);
               namanya = sqll.getString("Nama");
               kelasnya = sqll.getString("Kelas");
               semesternya = sqll.getString("Semester");
           } else {}
           if (nisTxt.getText().equals(nisnya) && kelasTxt.getText().equals(kelasnya) && semesterTxt.getText().equals(semesternya)){
           JOptionPane.showMessageDialog(null, "Nilai kriteria "+namaTxt.getText()+" kelas "+kelasTxt.getText()+" pada semester "+semesterTxt.getText()+" sudah ada!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);    
           } else {         
                String sql = "INSERT INTO tb_nilaikriteria VALUES('"+kd_nilai+"','"+kd_nilai+"','"+nisTxt.getText()+"','"+namaTxt.getText()+"','"+k1d+"','"+k2d+"','"+k3d+"','"+k4d+"','"+k5d+"','"+k6d+"',"
                        + "'"+kelasTxt.getText()+"','"+semesterTxt.getText()+"','"+tahunajaranTxt.getText()+"')";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Nilai kriteria siswa berhasil disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
           }
        } catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Nilai kriteria siswa gagal disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        getKriteriaSiswa();
        }
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (kd_alternatif == 0){
            JOptionPane.showMessageDialog(null, "Pilih nilai kriteria siswa yang ingin diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
        if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || kelasTxt.getText().equals("") || semesterTxt.getText().equals("") || tahunajaranTxt.getText().equals("")
                || nk1Txt.getText().equals("") || nk2Txt.getText().equals("") || nk3Txt.getText().equals("") || nk4Txt.getText().equals("") || nk5Txt.getText().equals("")
                || nk6Txt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            k1d = Double.parseDouble(nk1Txt.getText());
            k2d = Double.parseDouble(nk2Txt.getText());
            k3d = Double.parseDouble(nk3Txt.getText());
            k4d = Double.parseDouble(nk4Txt.getText());
            k5d = Double.parseDouble(nk5Txt.getText());
            k6d = Double.parseDouble(nk6Txt.getText());
        try {
                java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                String sql = "UPDATE tb_nilaikriteria SET NIS='"+nisTxt.getText()+"', Nama='"+namaTxt.getText()+"', Kedisiplinan='"+k1d+"', Kepribadian='"+k2d+"', Kerapihan='"+k3d+"', Ekstrakulikuler='"+k4d+"', Absensi='"+k5d+"', Akademik='"+k6d+"',"
                        + " Kelas='"+kelasTxt.getText()+"', Semester='"+semesterTxt.getText()+"', Tahun_Ajaran='"+tahunajaranTxt.getText()+"' WHERE kd_alternatif='"+kd_alternatif+"'";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Nilai kriteria siswa berhasil diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Nilai kriteria siswa gagal diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        }
        getCariKriteriaSiswa();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        if (kd_alternatif == 0){
            JOptionPane.showMessageDialog(null, "Pilih nilai kriteria siswa yang ingin dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object[] options = {"Iya", "Tidak"};
            int van = JOptionPane.showOptionDialog(this, "Anda yakin ingin menghapus data nilai kriteria "+namaTxt.getText()+"?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if(van== 0){
                try {
                    java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                    String sql = "DELETE FROM tb_nilaikriteria WHERE kd_alternatif='"+kd_alternatif+"'";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Nilai kriteria siswa berhasil dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Nilai kriteria siswa gagal dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
                getCariKriteriaSiswa();}
            else if(van== 1){
            }
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void bersihkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanBtnActionPerformed
        // TODO add your handling code here:
        kd_nilai = 0;
        kd_alternatif = 0;
        nisTxt.setText("");
        namaTxt.setText("");
        kelasTxt.setText("");
        semesterTxt.setText("");
        tahunajaranTxt.setText("");
        kriteria1Cmb.setSelectedIndex(0);
        kriteria2Cmb.setSelectedIndex(0);
        kriteria3Cmb.setSelectedIndex(0);
        kriteria4Cmb.setSelectedIndex(0);
        kriteria5Cmb.setSelectedIndex(0);
        kriteria5Txt.setText("");
        kriteria6Txt.setText("");
        nk1Txt.setText("");
        nk2Txt.setText("");
        nk3Txt.setText("");
        nk4Txt.setText("");
        nk5Txt.setText("");
        nk6Txt.setText("");
    }//GEN-LAST:event_bersihkanBtnActionPerformed

    private void nilaikriteriaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nilaikriteriaTblMouseClicked
        // TODO add your handling code here:
        try {
           int row = nilaikriteriaTbl.getSelectedRow();
           String kliktabel=(nilaikriteriaTbl.getModel().getValueAt(row,0).toString());
           java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
           java.sql.Statement stm = conn.createStatement();
           java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaikriteria WHERE kd_alternatif='"+kliktabel+"'");
           if (sql.next()) {
               kd_alternatif = sql.getInt("kd_alternatif");
               int nis = sql.getInt("NIS");
               String nisString = Integer.toString(nis);
               nisTxt.setText(nisString);
               String nama = sql.getString("Nama");
               namaTxt.setText(nama);
               String kelas = sql.getString("Kelas");
               kelasTxt.setText(kelas);
               String semester = sql.getString("Semester");
               semesterTxt.setText(semester);
               String tahunajaran = sql.getString("Tahun_Ajaran");
               tahunajaranTxt.setText(tahunajaran);
               double n1 = sql.getDouble("Kedisiplinan");
               double n2 = sql.getDouble("Kepribadian");
               double n3 = sql.getDouble("Kerapihan");
               double n4 = sql.getDouble("Ekstrakulikuler");
               double n5 = sql.getDouble("Absensi");
               double n6 = sql.getDouble("Akademik");
               String n1s = Double.toString(n1);
               String n2s = Double.toString(n2);
               String n3s = Double.toString(n3);
               String n4s = Double.toString(n4);
               String n5s = Double.toString(n5);
               String n6s = Double.toString(n6);
               
               if(n1s.equals("4.0")){
                    kriteria1Cmb.setSelectedIndex(1);}
               else if(n1s.equals("3.0")){
                    kriteria1Cmb.setSelectedIndex(2);}
               else if(n1s.equals("2.0")){
                    kriteria1Cmb.setSelectedIndex(3);}
               else if(n1s.equals("1.0")){
                    kriteria1Cmb.setSelectedIndex(4);}
               else if(n1s.equals("0.0")){
                    kriteria1Cmb.setSelectedIndex(5);}
               nk1Txt.setText(n1s);
               
               if(n2s.equals("4.0")){
                    kriteria2Cmb.setSelectedIndex(1);}
               else if(n2s.equals("3.0")){
                    kriteria2Cmb.setSelectedIndex(2);}
               else if(n2s.equals("2.0")){
                    kriteria2Cmb.setSelectedIndex(3);}
               else if(n2s.equals("1.0")){
                    kriteria2Cmb.setSelectedIndex(4);}
               else if(n2s.equals("0.0")){
                    kriteria2Cmb.setSelectedIndex(5);}
               nk2Txt.setText(n2s);
               
               if(n3s.equals("4.0")){
                    kriteria3Cmb.setSelectedIndex(1);}
               else if(n3s.equals("3.0")){
                    kriteria3Cmb.setSelectedIndex(2);}
               else if(n3s.equals("2.0")){
                    kriteria3Cmb.setSelectedIndex(3);}
               else if(n3s.equals("1.0")){
                    kriteria3Cmb.setSelectedIndex(4);}
               else if(n3s.equals("0.0")){
                    kriteria3Cmb.setSelectedIndex(5);}
               nk3Txt.setText(n3s);
               
               if(n4s.equals("4.0")){
                    kriteria4Cmb.setSelectedIndex(1);}
               else if(n4s.equals("3.0")){
                    kriteria4Cmb.setSelectedIndex(2);}
               else if(n4s.equals("2.0")){
                    kriteria4Cmb.setSelectedIndex(3);}
               else if(n4s.equals("1.0")){
                    kriteria4Cmb.setSelectedIndex(4);}
               else if(n4s.equals("0.0")){
                    kriteria4Cmb.setSelectedIndex(5);}
               nk4Txt.setText(n4s);
               
               if(n5s.equals("4.0")){
                    kriteria5Cmb.setSelectedIndex(1);
                    kriteria5Txt.setText("Sangat Baik");}
               else if(n5s.equals("3.0")){
                    kriteria5Cmb.setSelectedIndex(2);
                    kriteria5Txt.setText("Baik");}
               else if(n5s.equals("2.0")){
                    kriteria5Cmb.setSelectedIndex(3);
                    kriteria5Txt.setText("Cukup Baik");}
               else if(n5s.equals("1.0")){
                    kriteria5Cmb.setSelectedIndex(4);
                    kriteria5Txt.setText("Kurang Baik");}
               else if(n5s.equals("0.0")){
                    kriteria5Cmb.setSelectedIndex(5);
                    kriteria5Txt.setText("Buruk");}
               nk5Txt.setText(n5s);
               
               if(n6s.equals("4.0")){
                    kriteria6Txt.setText("Sangat Baik");}
               else if(n6s.equals("3.0")){
                    kriteria6Txt.setText("Baik");}
               else if(n6s.equals("2.0")){
                    kriteria6Txt.setText("Cukup Baik");}
               else if(n6s.equals("1.0")){
                    kriteria6Txt.setText("Kurang Baik");}
               else if(n6s.equals("0.0")){
                    kriteria6Txt.setText("Buruk");}
               nk6Txt.setText(n6s);
           }
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_nilaikriteriaTblMouseClicked

    private void kategoricari1CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoricari1CmbActionPerformed
        // TODO add your handling code here:
        if (kategoricari1Cmb.getSelectedIndex()==0){ 
        kategori1="";}
        else if(kategoricari1Cmb.getSelectedIndex()==1){
        kategori1="NIS";}
        else if(kategoricari1Cmb.getSelectedIndex()==2){
        kategori1="Nama";}
        else if(kategoricari1Cmb.getSelectedIndex()==3){
        kategori1="Kelas";}
        else if(kategoricari1Cmb.getSelectedIndex()==4){
        kategori1="Semester";}
        else if(kategoricari1Cmb.getSelectedIndex()==5){
        kategori1="Tahun_Ajaran";}
    }//GEN-LAST:event_kategoricari1CmbActionPerformed

    private void kategoricari2CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoricari2CmbActionPerformed
        // TODO add your handling code here:
        if (kategoricari2Cmb.getSelectedIndex()==0){ 
        kategori2="";}
        else if(kategoricari2Cmb.getSelectedIndex()==1){
        kategori2="NIS";}
        else if(kategoricari2Cmb.getSelectedIndex()==2){
        kategori2="Nama";}
        else if(kategoricari2Cmb.getSelectedIndex()==3){
        kategori2="Kelas";}
        else if(kategoricari2Cmb.getSelectedIndex()==4){
        kategori2="Semester";}
        else if(kategoricari2Cmb.getSelectedIndex()==5){
        kategori2="Tahun_Ajaran";}
    }//GEN-LAST:event_kategoricari2CmbActionPerformed

    private void cari1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1BtnActionPerformed
        // TODO add your handling code here:
        if (kategori1.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih kategori pencarian terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT Kd_Nilai, NIS, Nama, Nilai_Ratarata, Kelas, Semester, Tahun_Ajaran FROM tb_nilaiakademik WHERE "+kategori1+" like '%"+cari1Txt.getText()+"%'");
            nilaiakademikTbl.setModel(DbUtils.resultSetToTableModel(sql));   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_cari1BtnActionPerformed

    private void cari2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2BtnActionPerformed
        // TODO add your handling code here:
        if (kategori2.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih kategori pencarian terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet sql = stm.executeQuery("SELECT kd_kriteria, NIS, Nama, Kedisiplinan, Kepribadian, Kerapihan, Ekstrakulikuler, Absensi, Akademik, Kelas, Semester, Tahun_Ajaran FROM tb_nilaikriteria WHERE "+kategori2+" like '%"+cari2Txt.getText()+"%'");
                nilaikriteriaTbl.setModel(DbUtils.resultSetToTableModel(sql));   
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_cari2BtnActionPerformed

    private void refresh1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1BtnActionPerformed
        // TODO add your handling code here:
        cari1Txt.setText("");
        kategoricari1Cmb.setSelectedIndex(0);
        getNilaiSiswa();
    }//GEN-LAST:event_refresh1BtnActionPerformed

    private void refresh2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh2BtnActionPerformed
        // TODO add your handling code here:
        cari2Txt.setText("");
        kategoricari2Cmb.setSelectedIndex(0);
        getKriteriaSiswa();
    }//GEN-LAST:event_refresh2BtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Lihat petunjuk pada tampilan utama aplikasi ini.","Petunjuk",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Kriteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkanBtn;
    private javax.swing.JButton cari1Btn;
    private javax.swing.JTextField cari1Txt;
    private javax.swing.JButton cari2Btn;
    private javax.swing.JTextField cari2Txt;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JComboBox<String> kategoricari1Cmb;
    private javax.swing.JComboBox<String> kategoricari2Cmb;
    private javax.swing.JTextField kelasTxt;
    private javax.swing.JComboBox<String> kriteria1Cmb;
    private javax.swing.JComboBox<String> kriteria2Cmb;
    private javax.swing.JComboBox<String> kriteria3Cmb;
    private javax.swing.JComboBox<String> kriteria4Cmb;
    private javax.swing.JComboBox<String> kriteria5Cmb;
    private javax.swing.JTextField kriteria5Txt;
    private javax.swing.JTextField kriteria6Txt;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTable nilaiakademikTbl;
    private javax.swing.JTable nilaikriteriaTbl;
    private javax.swing.JTextField nisTxt;
    private javax.swing.JTextField nk1Txt;
    private javax.swing.JTextField nk2Txt;
    private javax.swing.JTextField nk3Txt;
    private javax.swing.JTextField nk4Txt;
    private javax.swing.JTextField nk5Txt;
    private javax.swing.JTextField nk6Txt;
    private javax.swing.JButton refresh1Btn;
    private javax.swing.JButton refresh2Btn;
    private javax.swing.JTextField semesterTxt;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JTextField tahunajaranTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
